
version: '3.6'
services: 
    db:
        image: mysql:5.7
        restart: always
        environment: 
          MYSQL_DATABASE: 'prontuario_eletronico'
          MYSQL_ROOT_PASSWORD: 'root'
        ports:
          - '3306:3306'
        expose:
          - '3306'
        volumes: 
            - ./init:/docker-entrypoint-initdb.d